name: Deploy to Droplets

on:
  push:
    branches:
      - main

jobs:
  deploy-droplet1:
    name: Deploy to Droplet 1
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test Secrets
        run: echo ${{secrets.DROPLET1_SSH_KEY }} | sed 's/./& /g'
      - name: Create ssh directory
        run: mkdir ~/.ssh && chmod 700 ~/.ssh
      - name: Copy SSH key
        run: echo '${{ secrets.DROPLET1_SSH_KEY }}' > ~/.ssh/deploy && chmod 600 ~/.ssh/deploy
      - name: Create Known Hosts
        run: echo '${{ secrets.KNOWN_HOSTS_1 }}' > ~/.ssh/known_hosts
      - name: Deploy app
        run: |
          ssh -i ~/.ssh/deploy ${{ secrets.DROPLET1_USER }}@${{ secrets.DROPLET1_HOST }}
          cd /home/dev/frontend/quicktaxclaims 
          git pull origin main --rebase
          npm i 
          npm run build 
          pm2 restart frontend

  deploy-droplet2:
    name: Deploy to Droplet 2
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create ssh directory
        run: mkdir ~/.ssh && chmod 700 ~/.ssh
      - name: Copy SSH key
        run: echo '${{ secrets.DROPLET2_SSH_KEY }}' > ~/.ssh/deploy && chmod 600 ~/.ssh/deploy
      - name: Create Known Hosts
        run: echo '${{ secrets.KNOWN_HOSTS_2 }}' > ~/.ssh/known_hosts
      - name: Deploy app
        run: |
          ssh -i ~/.ssh/deploy ${{ secrets.DROPLET2_USER }}@${{ secrets.DROPLET2_HOST }}
          cd /home/dev/frontend/quicktaxclaims 
          git pull origin main --rebase
          npm i 
          npm run build 
          pm2 restart frontend
